version: '3.3'
services:
  spring_rabbitmq:
    container_name: spring_rabbitmq
    image: rabbitmq:3.7-management
    ports:
      - 5672:5672
      - 15672:15672
  spring_zipkin:
    container_name: spring_zipking
    image: openzipkin/zipkin
    ports:
      - 9411:9411