spring.application.name: eureka-server
logging.level.com.netflix: DEBUG
management:
  security:
    enabled: false

server:
  port: 8761

eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
